[package]
name = "mxl-sys"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]

[build-dependencies]
bindgen.workspace = true
cmake = "0.1.54"

[features]
mxl-not-built = []
